version: '3'

services:
  app: &base_app
    env_file:
      - .env
    restart: always
    build:
      context: .
    ports:
      - "9999:9999"
    volumes:
      - .:/app

  migrate_init:
    <<: *base_app
    command: flask db init

  migrate_db:
    <<: *base_app
    command: flask db migrate

  db:
    env_file:
      - .env
    image: postgres:15.4-alpine3.18
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql